# Generated by Django 5.2.12 on 2026-03-18 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='portfolio_l_created_720a28_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'web'), ('crm', 'crm'), ('design', 'design'), ('brand', 'brand')], max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('detailed_page', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published'], name='portfolio_p_publish_f4feee_idx'), models.Index(fields=['category'], name='portfolio_p_categor_e9da5b_idx')],
            },
        ),
    ]
