# Generated by Django 5.1.4 on 2026-03-19 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('block_size', models.CharField(choices=[('sm', 'sm'), ('md', 'md'), ('lg', 'lg'), ('full', 'full')], default='md', max_length=10)),
                ('object_fit', models.CharField(choices=[('cover', 'cover'), ('contain', 'contain')], default='cover', max_length=10)),
                ('aspect_ratio', models.CharField(blank=True, choices=[('auto', 'auto'), ('square', 'square'), ('video', 'video'), ('portrait', 'portrait')], default='auto', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='portfolioproject',
            name='portfolio_p_categor_e9da5b_idx',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='detailed_page',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image_url',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='client_industry',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/hero/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='live_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='process',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('websites', 'websites'), ('landing', 'landing'), ('ecommerce', 'ecommerce'), ('crm', 'crm'), ('digital_product', 'digital_product'), ('branding', 'branding')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='results',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='technologies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_0adcb4_idx'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioproject'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project'], name='portfolio_p_project_9a8570_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['sort_order'], name='portfolio_p_sort_or_b82548_idx'),
        ),
    ]
