# Generated by Django 5.1.4 on 2026-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='service_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
