# Generated by Django 5.1.4 on 2026-03-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioproject_service_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsubmission',
            name='budget',
        ),
    ]
