# Generated by Django 5.1.4 on 2026-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_leadsubmission_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='home_filter',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
